version: '3.3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./record_pets_project/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
  nginx:
    build: ./infra/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static