# Generated by Django 5.0.7 on 2024-07-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_petphoto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('DG', 'dog'), ('CT', 'cat')], max_length=50, verbose_name='Вид'),
        ),
    ]
